-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 17:15:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AllBreads
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AllBreads
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AllBreads` DEFAULT CHARACTER SET utf8 ;
USE `AllBreads` ;

-- -----------------------------------------------------
-- Table `AllBreads`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`PRODUCTO` (
  `ID` INT NOT NULL,
  `CANTIDAD` INT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`CLIENTES` (
  `DNI` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `TELEFONO` INT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`PROVEEDOR` (
  `ID` INT NOT NULL,
  `RAZON SOCIAL` VARCHAR(45) NULL,
  `TIPO PRODUCTO` VARCHAR(45) NULL,
  `TELEFONO` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`ORDEN DE COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`ORDEN DE COMPRA` (
  `NRO_ORDEN` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(45) NULL,
  `CANT_ORDEN` INT NULL,
  `TIPO_PRODUCTO` VARCHAR(45) NULL,
  `PROVEEDOR_ID` INT NOT NULL,
  PRIMARY KEY (`NRO_ORDEN`),
  INDEX `fk_ORDEN DE COMPRA_PROVEEDOR1_idx` (`PROVEEDOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEN DE COMPRA_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_ID`)
    REFERENCES `AllBreads`.`PROVEEDOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`ORDEN DE DESPACHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`ORDEN DE DESPACHO` (
  `NUM_DESPACHO` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(45) NULL,
  `CANT_DESPACHO` INT NULL,
  `DNI` INT NOT NULL,
  `TIPO _PRODUCTO` VARCHAR(45) NULL,
  PRIMARY KEY (`NUM_DESPACHO`),
  INDEX `DNI_idx` (`DNI` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `AllBreads`.`CLIENTES` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`ORDEN DE DESPACHO_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`ORDEN DE DESPACHO_has_PRODUCTO` (
  `ORDEN DE DESPACHO_ID` INT NOT NULL,
  `PRODUCTO_ID` INT NOT NULL,
  PRIMARY KEY (`ORDEN DE DESPACHO_ID`, `PRODUCTO_ID`),
  INDEX `fk_ORDEN DE DESPACHO_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_ID` ASC) VISIBLE,
  INDEX `fk_ORDEN DE DESPACHO_has_PRODUCTO_ORDEN DE DESPACHO1_idx` (`ORDEN DE DESPACHO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ORDEN DE DESPACHO_has_PRODUCTO_ORDEN DE DESPACHO1`
    FOREIGN KEY (`ORDEN DE DESPACHO_ID`)
    REFERENCES `AllBreads`.`ORDEN DE DESPACHO` (`NUM_DESPACHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDEN DE DESPACHO_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `AllBreads`.`PRODUCTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AllBreads`.`PRODUCTO_has_ORDEN DE COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AllBreads`.`PRODUCTO_has_ORDEN DE COMPRA` (
  `PRODUCTO_ID` INT NOT NULL,
  `ORDEN DE COMPRA_ID` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_ID`, `ORDEN DE COMPRA_ID`),
  INDEX `fk_PRODUCTO_has_ORDEN DE COMPRA_ORDEN DE COMPRA1_idx` (`ORDEN DE COMPRA_ID` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_ORDEN DE COMPRA_PRODUCTO1_idx` (`PRODUCTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_ORDEN DE COMPRA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `AllBreads`.`PRODUCTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_ORDEN DE COMPRA_ORDEN DE COMPRA1`
    FOREIGN KEY (`ORDEN DE COMPRA_ID`)
    REFERENCES `AllBreads`.`ORDEN DE COMPRA` (`NRO_ORDEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
